var e,h,l;var m;m||(m=typeof Module !== 'undefined' ? Module : {});m.Ea||(m.Ea=0,m.Mb=0);m.Ea++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.Ua?m.R[a].loaded=c.loaded:(d.Ua=!0,m.R||(m.R={}),m.R[a]={loaded:c.loaded,total:f});var g=f=c=0,k;for(k in m.R){var r=m.R[k];c+=r.total;f+=r.loaded;g++}c=Math.ceil(c*m.Ea/g);m.setStatus&&m.setStatus("Downloading data... ("+f+"/"+c+")")}else!m.R&&m.setStatus&&m.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){m.Mb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.Ib=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();m.removeRunDependency("datafile_../../game/bin/colorsense.data")}m.FS_createPath("/","assets",!0,!0);m.FS_createPath("/assets","sfx",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;m.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.Ib.subarray(this.start,this.end))},finish:function(a){m.FS_createDataFile(this.name,null,a,!0,!0,!0);m.removeRunDependency("fp "+this.name);this.requests[this.name]=
null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].audio)).open("GET",d[f].filename);m.addRunDependency("datafile_../../game/bin/colorsense.data");m.vb||(m.vb={});m.vb["../../game/bin/colorsense.data"]={He:!1};p?(c(p),p=null):k=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof m.locateFilePackage||m.locateFile||(m.locateFile=m.locateFilePackage,n("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=m.locateFile?m.locateFile("colorsense.data",""):"colorsense.data",g=a.Se,k=null,p=m.getPreloadedPackage?m.getPreloadedPackage(f,g):null;
p||b(f,g,function(a){k?(k(a),k=null):p=a},c);m.calledRun?d():(m.preRun||(m.preRun=[]),m.preRun.push(d))})({files:[{start:0,audio:0,end:49895,filename:"/assets/Comfortaa-Regular.png"},{start:49895,audio:0,end:319257,filename:"/assets/gfx@4x.png"},{start:319257,audio:0,end:375734,filename:"/assets/gfx.png"},{start:375734,audio:0,end:377907,filename:"/assets/gfx@2x.bin"},{start:377907,audio:0,end:378345,filename:"/assets/2d.vert.glsl"},{start:378345,audio:0,end:390180,filename:"/assets/Comfortaa-Regular.bin"},
{start:390180,audio:0,end:392353,filename:"/assets/gfx@4x.bin"},{start:392353,audio:0,end:517299,filename:"/assets/gfx@2x.png"},{start:517299,audio:0,end:519952,filename:"/assets/mini.font"},{start:519952,audio:0,end:522125,filename:"/assets/gfx.bin"},{start:522125,audio:0,end:522438,filename:"/assets/2d.frag.glsl"},{start:522438,audio:0,end:525685,filename:"/assets/mini@2x.bin"},{start:525685,audio:0,end:528125,filename:"/assets/mini@4x.png"},{start:528125,audio:0,end:539960,filename:"/assets/Comfortaa-Regular@4x.bin"},
{start:539960,audio:0,end:540892,filename:"/assets/mini.png"},{start:540892,audio:0,end:649826,filename:"/assets/Comfortaa-Regular@2x.png"},{start:649826,audio:0,end:651217,filename:"/assets/mini@2x.png"},{start:651217,audio:0,end:654464,filename:"/assets/mini@4x.bin"},{start:654464,audio:0,end:654894,filename:"/assets/blur.frag.glsl"},{start:654894,audio:0,end:655930,filename:"/assets/luma.frag.glsl"},{start:655930,audio:0,end:910531,filename:"/assets/Comfortaa-Regular@4x.png"},{start:910531,audio:0,
end:915468,filename:"/assets/Comfortaa-Regular.font"},{start:915468,audio:0,end:927303,filename:"/assets/Comfortaa-Regular@2x.bin"},{start:927303,audio:0,end:930550,filename:"/assets/mini.bin"},{start:930550,audio:0,end:969958,filename:"/assets/gfx.sg"},{start:969958,audio:1,end:1009499,filename:"/assets/sfx/timebonus.mp3"},{start:1009499,audio:1,end:1024770,filename:"/assets/sfx/firework.mp3"},{start:1024770,audio:1,end:1028530,filename:"/assets/sfx/click.mp3"},{start:1028530,audio:1,end:1037724,
filename:"/assets/sfx/down.mp3"},{start:1037724,audio:1,end:1687591,filename:"/assets/sfx/music.mp3"},{start:1687591,audio:1,end:1691039,filename:"/assets/sfx/out.mp3"},{start:1691039,audio:1,end:1695635,filename:"/assets/sfx/over.mp3"},{start:1695635,audio:1,end:1714442,filename:"/assets/sfx/next_level.mp3"}],remote_package_size:1714442,package_uuid:"b9198a8a-5594-4301-b6da-090577fa9a35"});var aa={},q;for(q in m)m.hasOwnProperty(q)&&(aa[q]=m[q]);m.arguments=[];m.thisProgram="./this.program";
m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ba=!1,t=!1,u=!1,ca=!1;ba="object"===typeof window;t="function"===typeof importScripts;u="object"===typeof process&&"function"===typeof require&&!ba&&!t;ca=!ba&&!u&&!t;var x="";
if(u){x=__dirname+"/";var da,ea;m.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",
y);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ba||t)t?
x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ha=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),n=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(q in aa)aa.hasOwnProperty(q)&&(m[q]=aa[q]);aa=void 0;function ia(a){ja||(ja={});ja[a]||(ja[a]=1,n(a))}
var ja,ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},la=0;"object"!==typeof WebAssembly&&n("no native wasm support detected");var ma,z=!1;function assert(a,b){a||y("Assertion failed: "+b)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function pa(a,b){return a?oa(A,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ra(a){var b=qa(a)+1,c=sa(b);C(a,ta,c,b);return c}function ua(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,ta,A,va,wa,D,xa,E,F;
function ya(){m.HEAP8=ta=new Int8Array(buffer);m.HEAP16=va=new Int16Array(buffer);m.HEAP32=D=new Int32Array(buffer);m.HEAPU8=A=new Uint8Array(buffer);m.HEAPU16=wa=new Uint16Array(buffer);m.HEAPU32=xa=new Uint32Array(buffer);m.HEAPF32=E=new Float32Array(buffer);m.HEAPF64=F=new Float64Array(buffer)}var G=m.TOTAL_MEMORY||16777216;5242880>G&&n("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(ma=new WebAssembly.Memory({initial:G/65536}),buffer=ma.buffer):buffer=new ArrayBuffer(G),m.buffer=buffer);ya();D[9464]=5280992;function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.G;"number"===typeof c?void 0===b.J?m.dynCall_v(c):m.dynCall_vi(c,b.J):c(void 0===b.J?null:b.J)}}}var Aa=[],Ba=[],Ca=[],Da=[],Ea=[],Fa=!1;
function Ga(){Fa||(Fa=!0,m.noFSInit||Ha||(Ha=!0,Ia(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?I("/dev","stdin",m.stdin):Ja("/dev/tty","/dev/stdin"),m.stdout?I("/dev","stdout",null,m.stdout):Ja("/dev/tty","/dev/stdout"),m.stderr?I("/dev","stderr",null,m.stderr):Ja("/dev/tty1","/dev/stderr"),Ka("/dev/stdin","r"),Ka("/dev/stdout","w"),Ka("/dev/stderr","w")),za(Ba))}function La(){var a=m.preRun.shift();Aa.unshift(a)}var Ma=0,Na=null,Oa=null;
function Pa(){Ma++;m.monitorRunDependencies&&m.monitorRunDependencies(Ma)}function Qa(){Ma--;m.monitorRunDependencies&&m.monitorRunDependencies(Ma);if(0==Ma&&(null!==Na&&(clearInterval(Na),Na=null),Oa)){var a=Oa;Oa=null;a()}}m.preloadedImages={};m.preloadedAudios={};function Sa(){var a=Ta;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ta="colorsense.wasm";
if(!Sa()){var Ua=Ta;Ta=m.locateFile?m.locateFile(Ua,x):x+Ua}function Va(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(Ta);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}
function Wa(){return m.wasmBinary||!ba&&!t||"function"!==typeof fetch?new Promise(function(a){a(Va())}):fetch(Ta,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ta+"'";return a.arrayBuffer()}).catch(function(){return Va()})}
function Xa(a){function b(a){m.asm=a.exports;Qa("wasm-instantiate")}function c(a){b(a.instance)}function d(a){Wa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){n("failed to asynchronously prepare wasm: "+a);y(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ka};Pa("wasm-instantiate");if(m.instantiateWasm)try{return m.instantiateWasm(f,b)}catch(g){return n("Module.instantiateWasm callback failed with error: "+g),!1}m.wasmBinary||"function"!==
typeof WebAssembly.instantiateStreaming||Sa()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Ta,{credentials:"same-origin"}),f).then(c,function(a){n("wasm streaming compile failed: "+a);n("falling back to ArrayBuffer instantiation");d(c)});return{}}m.asm=function(a,b){b.memory=ma;b.table=new WebAssembly.Table({initial:1243,maximum:1243,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Xa(b)};Ba.push({G:function(){Ya()}});
function Za(a){m.___errno_location&&(D[m.___errno_location()>>2]=a);return a}function $a(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ab(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$a(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function cb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function db(){var a=Array.prototype.slice.call(arguments,0);return ab(a.join("/"))}function L(a,b){return ab(a+"/"+b)}
function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$a(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var fb=[];function gb(a,b){fb[a]={input:[],output:[],U:b};hb(a,ib)}
var ib={open:function(a){var b=fb[a.node.rdev];if(!b)throw new M(N.Ba);a.tty=b;a.seekable=!1},close:function(a){a.tty.U.flush(a.tty)},flush:function(a){a.tty.U.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.U.hb)throw new M(N.Sa);for(var f=0,g=0;g<d;g++){try{var k=a.tty.U.hb(a.tty)}catch(p){throw new M(N.Qa);}if(void 0===k&&0===f)throw new M(N.zb);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.U.Ma)throw new M(N.Sa);
try{for(var f=0;f<d;f++)a.tty.U.Ma(a.tty,b[c+f])}catch(g){throw new M(N.Qa);}d&&(a.node.timestamp=Date.now());return f}},kb={hb:function(a){if(!a.input.length){var b=null;if(u){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=jb(b)}return a.input.shift()},Ma:function(a,b){null===b||10===b?(ha(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(oa(a.output,0)),a.output=[])}},lb={Ma:function(a,b){null===b||10===b?(n(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(n(oa(a.output,0)),a.output=[])}},O={v:null,l:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(N.Db);O.v||(O.v={dir:{node:{B:O.f.B,j:O.f.j,lookup:O.f.lookup,ea:O.f.ea,rename:O.f.rename,unlink:O.f.unlink,rmdir:O.f.rmdir,readdir:O.f.readdir,symlink:O.f.symlink},stream:{H:O.g.H}},file:{node:{B:O.f.B,j:O.f.j},stream:{H:O.g.H,read:O.g.read,write:O.g.write,Ta:O.g.Ta,qb:O.g.qb,sb:O.g.sb}},link:{node:{B:O.f.B,j:O.f.j,readlink:O.f.readlink},
stream:{}},Ya:{node:{B:O.f.B,j:O.f.j},stream:mb}});c=nb(a,b,c,d);P(c.mode)?(c.f=O.v.dir.node,c.g=O.v.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=O.v.file.node,c.g=O.v.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=O.v.link.node,c.g=O.v.link.stream):8192===(c.mode&61440)&&(c.f=O.v.Ya.node,c.g=O.v.Ya.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},Ie:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},Je:function(a){return a.c?a.c.subarray?
a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},ab:function(a,b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},cc:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{B:function(a){var b=
{};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.K=4096;b.blocks=Math.ceil(b.size/b.K);return b},j:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.cc(a,b.size)},lookup:function(){throw ob[N.Bb];
},ea:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(P(a.mode)){try{var d=pb(b,c)}catch(g){}if(d)for(var f in d.c)throw new M(N.Ra);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.c)throw new M(N.Ra);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==
(a.mode&61440))throw new M(N.s);return a.link}},g:{read:function(a,b,c,d,f){var g=a.node.c;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===f)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(f+d<=a.h)return a.c.set(b.subarray(c,c+d),
f),d}O.ab(a,f+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.c[f+g]=b[c+g];a.h=Math.max(a.h,f+d);return d},H:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new M(N.s);return b},Ta:function(a,b,c){O.ab(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},qb:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new M(N.Ba);c=a.node.c;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.h)c.subarray?c=c.subarray(f,
f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Q(d);if(!d)throw new M(N.Cb);b.set(c,d)}else a=!1,d=c.byteOffset;return{Re:d,ye:a}},sb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new M(N.Ba);if(f&2)return 0;O.g.write(a,b,0,d,c,!1);return 0}}},R={pa:!1,mc:function(){R.pa=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);R.cb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Va:function(a){return Buffer.Ua?
Buffer.from(a):new Buffer(a)},l:function(a){assert(u);return R.createNode(null,"/",R.gb(a.Ka.root),0)},createNode:function(a,b,c){if(!P(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new M(N.s);a=nb(a,b,c);a.f=R.f;a.g=R.g;return a},gb:function(a){try{var b=fs.lstatSync(a);R.pa&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}return b.mode},m:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.l.Ka.root);b.reverse();return db.apply(null,b)},
Nb:function(a){a&=-2656257;var b=0,c;for(c in R.cb)a&c&&(b|=R.cb[c],a^=c);if(a)throw new M(N.s);return b},f:{B:function(a){a=R.m(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}R.pa&&!b.K&&(b.K=4096);R.pa&&!b.blocks&&(b.blocks=(b.size+b.K-1)/b.K|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,K:b.K,blocks:b.blocks}},j:function(a,b){var c=R.m(a);try{void 0!==b.mode&&(fs.chmodSync(c,
b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},lookup:function(a,b){var c=L(R.m(a),b);c=R.gb(c);return R.createNode(a,b,c)},ea:function(a,b,c,d){a=R.createNode(a,b,c,d);b=R.m(a);try{P(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new M(N[f.code]);}return a},rename:function(a,b,c){a=R.m(a);b=L(R.m(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);
}},unlink:function(a,b){a=L(R.m(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},rmdir:function(a,b){a=L(R.m(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},readdir:function(a){a=R.m(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new M(N[b.code]);}},symlink:function(a,b,c){a=L(R.m(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},readlink:function(a){var b=R.m(a);try{return b=fs.readlinkSync(b),
b=qb.relative(qb.resolve(a.l.Ka.root),b)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}}},g:{open:function(a){var b=R.m(a.node);try{32768===(a.node.mode&61440)&&(a.ga=fs.openSync(b,R.Nb(a.flags)))}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.ga&&fs.closeSync(a.ga)}catch(b){if(!b.code)throw b;throw new M(N[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.ga,R.Va(b.buffer),c,d,f)}catch(g){throw new M(N[g.code]);
}},write:function(a,b,c,d,f){try{return fs.writeSync(a.ga,R.Va(b.buffer),c,d,f)}catch(g){throw new M(N[g.code]);}},H:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ga).size}catch(d){throw new M(N[d.code]);}if(0>b)throw new M(N.s);return b}}},rb=null,sb={},tb=[],ub=1,S=null,vb=!0,wb={},M=null,ob={};
function T(a,b){a=eb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={eb:!0,Na:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Na)throw new M(40);a=$a(a.split("/").filter(function(a){return!!a}),!1);var f=rb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=pb(f,a[d]);c=L(c,a[d]);f.fa&&(!g||g&&b.eb)&&(f=f.fa.root);if(!g||b.Fa)for(g=0;40960===(f.mode&61440);)if(f=xb(c),c=eb(bb(c),f),f=T(c,{Na:b.Na}).node,40<g++)throw new M(40);}return{path:c,node:f}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.l.rb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function Ab(a){var b=zb(a.parent.id,a.name);a.S=S[b];S[b]=a}function pb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.f.lookup?0:13)throw new M(c,a);for(c=S[zb(a.id,b)];c;c=c.S){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function nb(a,b,c,d){Cb||(Cb=function(a,b,c,d){a||(a=this);this.parent=a;this.l=a.l;this.fa=null;this.id=ub++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},Cb.prototype={},Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Xb:{get:function(){return P(this.mode)}},Wb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Cb(a,b,c,d);Ab(a);return a}function P(a){return 16384===(a&61440)}var Db={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}
function Fb(a,b){try{return pb(a,b),17}catch(c){}return Bb(a,"wx")}function Gb(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new M(24);}function Hb(a,b){Ib||(Ib=function(){},Ib.prototype={},Object.defineProperties(Ib.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ib,d;for(d in a)c[d]=a[d];a=c;b=Gb(b);a.fd=b;return tb[b]=a}var mb={open:function(a){a.g=sb[a.node.rdev].g;a.g.open&&a.g.open(a)},H:function(){throw new M(29);}};
function hb(a,b){sb[a]={g:b}}function Jb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new M(16);if(!c&&!d){var f=T(b,{eb:!1});b=f.path;f=f.node;if(f.fa)throw new M(16);if(!P(f.mode))throw new M(20);}b={type:a,Ka:{},rb:b,Zb:[]};a=a.l(b);a.l=b;b.root=a;c?rb=a:f&&(f.fa=b,f.l&&f.l.Zb.push(b))}function Kb(a,b,c){var d=T(a,{parent:!0}).node;a=cb(a);if(!a||"."===a||".."===a)throw new M(22);var f=Fb(d,a);if(f)throw new M(f);if(!d.f.ea)throw new M(1);return d.f.ea(d,a,b,c)}
function U(a,b){return Kb(a,(void 0!==b?b:511)&1023|16384,0)}function Lb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Kb(a,b|8192,c)}function Ja(a,b){if(!eb(a))throw new M(2);var c=T(b,{parent:!0}).node;if(!c)throw new M(2);b=cb(b);var d=Fb(c,b);if(d)throw new M(d);if(!c.f.symlink)throw new M(1);return c.f.symlink(c,b,a)}
function Mb(a){var b=T(a,{parent:!0}).node,c=cb(a),d=pb(b,c);a:{try{var f=pb(b,c)}catch(k){f=k.D;break a}var g=Bb(b,"wx");f=g?g:P(f.mode)?21:0}if(f)throw new M(f);if(!b.f.unlink)throw new M(1);if(d.fa)throw new M(16);try{wb.willDeletePath&&wb.willDeletePath(a)}catch(k){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.f.unlink(b,c);b=zb(d.parent.id,d.name);if(S[b]===d)S[b]=d.S;else for(b=S[b];b;){if(b.S===d){b.S=d.S;break}b=b.S}try{if(wb.onDeletePath)wb.onDeletePath(a)}catch(k){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function xb(a){a=T(a).node;if(!a)throw new M(2);if(!a.f.readlink)throw new M(22);return eb(yb(a.parent),a.f.readlink(a))}function Nb(a,b){var c;"string"===typeof a?c=T(a,{Fa:!0}).node:c=a;if(!c.f.j)throw new M(1);c.f.j(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Ka(a,b,c,d){if(""===a)throw new M(2);if("string"===typeof b){var f=Db[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=ab(a);try{g=T(a,{Fa:!(b&131072)}).node}catch(p){}}f=!1;if(b&64)if(g){if(b&128)throw new M(17);}else g=Kb(a,c,0),f=!0;if(!g)throw new M(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!P(g.mode))throw new M(20);if(!f&&(c=g?40960===(g.mode&61440)?40:P(g.mode)&&
("r"!==Eb(b)||b&512)?21:Bb(g,Eb(b)):2))throw new M(c);if(b&512){c=g;var k;"string"===typeof c?k=T(c,{Fa:!0}).node:k=c;if(!k.f.j)throw new M(1);if(P(k.mode))throw new M(21);if(32768!==(k.mode&61440))throw new M(22);if(c=Bb(k,"w"))throw new M(c);k.f.j(k,{size:0,timestamp:Date.now()})}b&=-641;d=Hb({node:g,path:yb(g),flags:b,seekable:!0,position:0,g:g.g,oc:[],error:!1},d);d.g.open&&d.g.open(d);!m.logReadFiles||b&1||(Ob||(Ob={}),a in Ob||(Ob[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{wb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),wb.onOpenFile(a,g))}catch(p){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function Pb(a){if(null===a.fd)throw new M(9);a.Ha&&(a.Ha=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{tb[a.fd]=null}a.fd=null}
function Qb(a,b,c){if(null===a.fd)throw new M(9);if(!a.seekable||!a.g.H)throw new M(29);if(0!=c&&1!=c&&2!=c)throw new M(22);a.position=a.g.H(a,b,c);a.oc=[]}
function Rb(a,b,c,d,f,g){if(0>d||0>f)throw new M(22);if(null===a.fd)throw new M(9);if(0===(a.flags&2097155))throw new M(9);if(P(a.node.mode))throw new M(21);if(!a.g.write)throw new M(22);a.flags&1024&&Qb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new M(29);b=a.g.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&wb.onWriteToFile)wb.onWriteToFile(a.path)}catch(p){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+p.message)}return b}
function Ia(){M||(M=function(a,b){this.node=b;this.jc=function(a){this.D=a};this.jc(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},M.prototype=Error(),M.prototype.constructor=M,[2].forEach(function(a){ob[a]=new M(a);ob[a].stack="<generic error, no stack>"}))}var Ha;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Tb(a,b,c,d){a=L("string"===typeof a?a:yb(a),b);return U(a,Sb(c,d))}
function Ub(a,b){a="string"===typeof a?a:yb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a,c);try{U(d)}catch(f){}a=d}}return d}function Vb(a,b,c,d){a=L("string"===typeof a?a:yb(a),b);c=Sb(c,d);return Kb(a,(void 0!==c?c:438)&4095|32768,0)}
function Wb(a,b,c,d,f,g){a=b?L("string"===typeof a?a:yb(a),b):a;d=Sb(d,f);f=Kb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Nb(f,d|146);a=Ka(f,"w");Rb(a,c,0,c.length,0,g);Pb(a);Nb(f,d)}return f}
function I(a,b,c,d){a=L("string"===typeof a?a:yb(a),b);b=Sb(!!c,!!d);I.lb||(I.lb=64);var f=I.lb++<<8|0;hb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,k=0;k<f;k++){try{var r=c()}catch(J){throw new M(5);}if(void 0===r&&0===g)throw new M(11);if(null===r||void 0===r)break;g++;b[d+k]=r}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(v){throw new M(5);}f&&(a.node.timestamp=
Date.now());return g}});return Lb(a,b,f)}function Xb(a,b,c){a=L("string"===typeof a?a:yb(a),b);return Ja(c,a)}
function Yb(a){if(a.Wb||a.Xb||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(m.read)try{a.c=jb(m.read(a.url)),a.h=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Za(5);return b}
function Zb(a,b,c,d,f){function g(){this.Ia=!1;this.la=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.ib(a/this.chunkSize|0)[b]}};g.prototype.ic=function(a){this.ib=a};g.prototype.Xa=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var k=this;k.ic(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof k.la[a]){var r=k.la;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==g&&p.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):jb(p.responseText||"");r[a]=d}if("undefined"===typeof k.la[a])throw Error("doXHR failed!");return k.la[a]});if(a||!b)g=b=1,g=b=this.ib(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Gb=b;this.Fb=
g;this.Ia=!0};if("undefined"!==typeof XMLHttpRequest){if(!t)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Ia||this.Xa();return this.Gb}},chunkSize:{get:function(){this.Ia||this.Xa();return this.Fb}}});var p=void 0}else p=c,k=void 0;var r=Vb(a,b,d,f);k?r.c=k:p&&(r.c=null,r.url=p);Object.defineProperties(r,{h:{get:function(){return this.c.length}}});var w={};
Object.keys(r.g).forEach(function(a){var b=r.g[a];w[a]=function(){if(!Yb(r))throw new M(5);return b.apply(null,arguments)}});w.read=function(a,b,c,d,f){if(!Yb(r))throw new M(5);a=a.node.c;if(f>=a.length)return 0;d=Math.min(a.length-f,d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};r.g=w;return r}
function $b(a,b,c,d,f,g,k,p,r,w){function v(c){function v(c){w&&w();p||Wb(a,b,c,d,f,r);g&&g();Qa(J)}var K=!1;m.preloadPlugins.forEach(function(a){!K&&a.canHandle(H)&&(a.handle(c,H,v,function(){k&&k();Qa(J)}),K=!0)});K||v(c)}e.oa();var H=b?eb(L(a,b)):a,J="cp "+H;Pa(J);"string"==typeof c?e.Hb(c,function(a){v(a)},k):v(c)}
var ac={},Cb,Ib,Ob,N={Db:1,Bb:2,le:3,bd:4,Qa:5,Sa:6,sc:7,Ed:8,Ab:9,Ic:10,zb:11,ve:11,Cb:12,tc:13,Vc:14,Qd:15,Gc:16,Uc:17,we:18,Ba:19,Sd:20,dd:21,s:22,zd:23,rd:24,L:25,se:26,Wc:27,Md:28,ke:29,he:30,sd:31,ae:32,Rc:33,ee:34,Id:42,Zc:43,Jc:44,gd:45,hd:46,jd:47,pd:48,te:49,Cd:50,ed:51,Oc:35,Fd:37,zc:52,Cc:53,xe:54,Ad:55,Dc:56,Ec:57,Pc:35,Fc:59,Od:60,Dd:61,pe:62,Nd:63,Jd:64,Kd:65,ge:66,Gd:67,wc:68,me:69,Kc:70,be:71,ud:72,Sc:73,Bc:74,Wd:76,Ac:77,fe:78,kd:79,ld:80,od:81,nd:82,md:83,Pd:38,Ra:39,vd:36,qd:40,
Xd:95,$d:96,Nc:104,Bd:105,xc:97,de:91,Ud:88,Ld:92,ie:108,Mc:111,uc:98,Lc:103,yd:101,wd:100,qe:110,Xc:112,Yc:113,ad:115,yc:114,Qc:89,td:90,ce:93,je:94,vc:99,xd:102,cd:106,Rd:107,re:109,ue:87,Tc:122,ne:116,Vd:95,Hd:123,$c:84,Yd:75,Hc:125,Td:131,Zd:130,oe:86},V=0;function W(){V+=4;return D[V-4>>2]}function bc(){var a=tb[W()];if(!a)throw new M(N.Ab);return a}var cc=0,dc=0,X=0,ec=0,fc=0,hc=null,ic=null,jc=!1;function kc(){for(var a=Y.length-1;0<=a;--a)lc(a);Y=[];mc=[]}var mc=[];
function nc(){if(oc&&pc.N)for(var a=0;a<mc.length;++a){var b=mc[a];mc.splice(a,1);--a;b.$e.apply(this,b.ze)}}var oc=0,pc=null,Y=[];function qc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function lc(a){var b=Y[a];b.target.removeEventListener(b.F,b.Kb,b.W);Y.splice(a,1)}
function rc(a){function b(b){++oc;pc=a;nc();a.$(b);nc();--oc}if(a.Y)a.Kb=b,a.target.addEventListener(a.F,b,a.W),Y.push(a),jc||(Da.push(kc),jc=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].F==a.F&&lc(c--)}var sc={},tc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Z(a){try{if(!a)return window;"number"===typeof a&&(a=tc[a]||pa(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function uc(){y()}function vc(a){a=ua(a);var b=m.buffer.byteLength;try{return-1!==ma.grow((a-b)/65536)?m.buffer=ma.buffer:null}catch(c){return null}}
function wc(a){if(2147418112<a)return!1;for(var b=Math.max(G,16777216);b<a;)536870912>=b?b=ua(2*b):b=Math.min(ua((3*b+2147483648)/4),2147418112);a=vc(b);if(!a||a.byteLength!=b)return!1;m.buffer=buffer=a;ya();G=b;return!0}function xc(a){"number"===typeof a&&(a=pa(a));return a&&"#canvas"!==a?"undefined"!==typeof h&&h.va[a]?h.va[a]:Z(a):"undefined"!==typeof h&&h.va.canvas?h.va.canvas:m.canvas}
function yc(a,b,c,d,f,g){cc||(cc=Q(164));a={target:Z(a),N:qc()?!1:!0,F:g,Y:d,$:function(a){a=a||window.event;var c=cc;C(a.key?a.key:"",A,c+0,32);C(a.code?a.code:"",A,c+32,32);D[c+64>>2]=a.location;D[c+68>>2]=a.ctrlKey;D[c+72>>2]=a.shiftKey;D[c+76>>2]=a.altKey;D[c+80>>2]=a.metaKey;D[c+84>>2]=a.repeat;C(a.locale?a.locale:"",A,c+88,32);C(a.char?a.char:"",A,c+120,32);D[c+152>>2]=a.charCode;D[c+156>>2]=a.keyCode;D[c+160>>2]=a.which;zc(d,f,c,b)&&a.preventDefault()},W:c};rc(a)}
e={b:{I:null,method:"",P:0,G:null,J:0,za:0,Aa:0,Da:0,wb:[],pause:function(){e.b.I=null;e.b.P++},resume:function(){e.b.P++;var a=e.b.za,b=e.b.Aa,c=e.b.G;e.b.G=null;Ac(c,0,!1,e.b.J,!0);Bc(a,b);e.b.I()},qc:function(){if(m.setStatus){var a=m.statusMessage||"Please wait...",b=e.b.Oa,c=e.b.Fe;b?b<c?m.setStatus(a+" ("+(c-b)+"/"+c+")"):m.setStatus(a):m.setStatus("")}},ec:function(a){if(!(z||m.preMainLoop&&!1===m.preMainLoop())){try{a()}catch(b){if(b instanceof fa)return;b&&"object"===typeof b&&b.stack&&n("exception thrown: "+
[b,b.stack]);throw b;}m.postMainLoop&&m.postMainLoop()}}},aa:!1,La:!1,Yb:[],workers:[],oa:function(){function a(){e.La=document.pointerLockElement===m.canvas||document.mozPointerLockElement===m.canvas||document.webkitPointerLockElement===m.canvas||document.msPointerLockElement===m.canvas}m.preloadPlugins||(m.preloadPlugins=[]);if(!e.Ub){e.Ub=!0;try{e.na=!0}catch(c){e.na=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}e.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:e.na?null:console.log("warning: no BlobBuilder");e.ka="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;m.ub||"undefined"!==typeof e.ka||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),m.ub=!0);m.preloadPlugins.push({canHandle:function(a){return!m.ub&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(e.na)try{c=
new Blob([a],{type:e.Ga(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:e.Ga(b)}))}catch(w){ia("Blob constructor present but fails: "+w+"; falling back to blob builder")}c||(c=new e.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=e.ka.createObjectURL(c),r=new Image;r.onload=function(){assert(r.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=r.width;c.height=r.height;c.getContext("2d").drawImage(r,0,0);m.preloadedImages[b]=
c;e.ka.revokeObjectURL(d);f&&f(a)};r.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};r.src=d}});m.preloadPlugins.push({canHandle:function(a){return!m.Oe&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){r||(r=!0,m.preloadedAudios[b]=c,f&&f(a))}function d(){r||(r=!0,m.preloadedAudios[b]=new Audio,g&&g())}var r=!1;if(e.na){try{var w=new Blob([a],{type:e.Ga(b)})}catch(H){return d()}w=e.ka.createObjectURL(w);var v=new Audio;v.addEventListener("canplaythrough",
function(){c(v)},!1);v.onerror=function(){if(!r){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,k=0;k<a.length;k++)for(f=f<<8|a[k],g+=8;6<=g;){var p=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");v.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(v)}};v.src=w;e.fc(function(){c(v)},1E4)}else return d()}});var b=m.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),m.elementPointerLock&&b.addEventListener("click",function(a){!e.La&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&m.ma&&a==m.canvas)return m.ma;var f;if(b){var g={antialias:!1,alpha:!1,mb:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof h&&(f=h.createContext(a,
g)))var p=h.getContext(f).M}else p=a.getContext("2d");if(!p)return null;c&&(b||assert("undefined"===typeof l,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),m.ma=p,b&&h.nb(f),m.cf=b,e.Yb.forEach(function(a){a()}),e.oa());return p},De:function(){},fb:!1,qa:void 0,V:void 0,requestFullscreen:function(a,b,c){function d(){e.aa=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=e.exitFullscreen,e.qa&&f.requestPointerLock(),e.aa=!0,e.V?e.kc():e.ja(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),e.V?e.lc():e.ja(f));if(m.onFullScreen)m.onFullScreen(e.aa);if(m.onFullscreen)m.onFullscreen(e.aa)}e.qa=a;e.V=b;e.yb=c;"undefined"===typeof e.qa&&(e.qa=!0);"undefined"===typeof e.V&&(e.V=!1);"undefined"===typeof e.yb&&(e.yb=null);var f=m.canvas;e.fb||(e.fb=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?g.requestFullscreen({ef:c}):g.requestFullscreen()},xb:function(a,b,c){n("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");e.xb=function(a,b,c){return e.requestFullscreen(a,b,c)};return e.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!e.aa)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},T:0,bb:function(a){var b=
Date.now();if(0===e.T)e.T=b+1E3/60;else for(;b+2>=e.T;)e.T+=1E3/60;setTimeout(a,Math.max(e.T-b,0))},requestAnimationFrame:function(a){"undefined"===typeof window?e.bb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||e.bb),window.requestAnimationFrame(a))},We:function(a){return function(){if(!z)return a.apply(null,arguments)}},
X:!0,ia:[],Pe:function(){e.X=!1},Ve:function(){e.X=!0;if(0<e.ia.length){var a=e.ia;e.ia=[];a.forEach(function(a){a()})}},Xe:function(a){return e.requestAnimationFrame(function(){z||(e.X?a():e.ia.push(a))})},fc:function(a,b){m.noExitRuntime=!0;return setTimeout(function(){z||(e.X?a():e.ia.push(a))},b)},Ye:function(a,b){m.noExitRuntime=!0;return setInterval(function(){z||e.X&&a()},b)},Ga:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",
mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ob:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Pb:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Ke:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=
100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},ta:0,ua:0,ra:0,sa:0,touches:{},kb:{},Ae:function(a){if(e.La)"mousemove"!=a.type&&"mozMovementX"in a?e.ra=e.sa=0:(e.ra=e.Ob(a),e.sa=e.Pb(a)),e.ta+=e.ra,e.ua+=e.sa;else{var b=m.canvas.getBoundingClientRect(),c=m.canvas.width,d=m.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==
typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.bf;if(void 0!==k)if(f=k.pageX-(f+b.left),g=k.pageY-(g+b.top),f*=c/b.width,g*=d/b.height,b={x:f,y:g},"touchstart"===a.type)e.kb[k.identifier]=b,e.touches[k.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=e.touches[k.identifier])||(a=b),e.kb[k.identifier]=a,e.touches[k.identifier]=b}else k=a.pageX-(f+b.left),a=a.pageY-(g+b.top),k*=c/b.width,a*=d/b.height,
e.ra=k-e.ta,e.sa=a-e.ua,e.ta=k,e.ua=a}},Hb:function(a,b,c,d){var f=d?"":"al "+a;m.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));f&&Qa(f)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});f&&Pa(f)},dc:[],Pa:function(){var a=m.canvas;e.dc.forEach(function(b){b(a.width,a.height)})},hc:function(a,b,c){e.ja(m.canvas,a,b);c||e.Pa()},hf:0,gf:0,kc:function(){e.ja(m.canvas);e.Pa()},lc:function(){e.ja(m.canvas);e.Pa()},ja:function(a,
b,c){b&&c?(a.rc=b,a.Rb=c):(b=a.rc,c=a.Rb);var d=b,f=c;m.forcedAspectRatio&&0<m.forcedAspectRatio&&(d/f<m.forcedAspectRatio?d=Math.round(f*m.forcedAspectRatio):f=Math.round(d/m.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}e.V?(a.width!=
d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},ff:{},tb:0,Le:function(){var a=e.tb;e.tb++;return a}};
function Bc(a,b){e.b.za=a;e.b.Aa=b;if(!e.b.G)return 1;if(0==a)e.b.I=function(){var a=Math.max(0,e.b.nc+b-uc())|0;setTimeout(e.b.wa,a)},e.b.method="timeout";else if(1==a)e.b.I=function(){e.requestAnimationFrame(e.b.wa)},e.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);t?(void 0===m.setImmediates&&(m.setImmediates=
[]),m.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}e.b.I=function(){setImmediate(e.b.wa)};e.b.method="immediate"}return 0}
function Ac(a,b,c,d,f){m.noExitRuntime=!0;assert(!e.b.G,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");e.b.G=a;e.b.J=d;var g="undefined"!==typeof d?function(){m.dynCall_vi(a,d)}:function(){m.dynCall_v(a)};var k=e.b.P;e.b.wa=function(){if(!z)if(0<e.b.wb.length){var a=Date.now(),b=e.b.wb.shift();b.G(b.J);if(e.b.Oa){var c=e.b.Oa,d=0==c%1?c-1:Math.floor(c);e.b.Oa=
b.Be?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");e.b.qc();k<e.b.P||setTimeout(e.b.wa,0)}else k<e.b.P||(e.b.Da=e.b.Da+1|0,1==e.b.za&&1<e.b.Aa&&0!=e.b.Da%e.b.Aa?e.b.I():(0==e.b.za&&(e.b.nc=uc()),"timeout"===e.b.method&&m.ma&&(n("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
e.b.method=""),e.b.ec(g),k<e.b.P||e.b.I()))};f||(b&&0<b?Bc(0,1E3/b):Bc(1,1),e.b.I());if(c)throw"SimulateInfiniteLoop";}
function Cc(a,b,c){F[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();D[a+8>>2]=b.screenX;D[a+12>>2]=b.screenY;D[a+16>>2]=b.clientX;D[a+20>>2]=b.clientY;D[a+24>>2]=b.ctrlKey;D[a+28>>2]=b.shiftKey;D[a+32>>2]=b.altKey;D[a+36>>2]=b.metaKey;va[a+40>>1]=b.button;va[a+42>>1]=b.buttons;D[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-hc;D[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-ic;if(m.canvas){var d=m.canvas.getBoundingClientRect();
D[a+60>>2]=b.clientX-d.left;D[a+64>>2]=b.clientY-d.top}else D[a+60>>2]=0,D[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},D[a+52>>2]=b.clientX-d.left,D[a+56>>2]=b.clientY-d.top):(D[a+52>>2]=0,D[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(hc=b.screenX,ic=b.screenY)}
function Dc(a,b,c,d,f,g){dc||(dc=Q(72));a=Z(a);c={target:a,N:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,F:g,Y:d,$:function(c){c=c||window.event;Cc(dc,c,a);zc(d,f,dc,b)&&c.preventDefault()},W:c};qc()&&"mousedown"==g&&(c.N=!1);rc(c)}
function Ec(a,b,c,d,f,g){ec||(ec=Q(36));"scroll"!=g||a?a=Z(a):a=document;rc({target:a,N:!1,F:g,Y:d,$:function(c){c=c||window.event;if(c.target==a){var g=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=ec;D[k>>2]=c.detail;D[k+
4>>2]=document.body.clientWidth;D[k+8>>2]=document.body.clientHeight;D[k+12>>2]=window.innerWidth;D[k+16>>2]=window.innerHeight;D[k+20>>2]=window.outerWidth;D[k+24>>2]=window.outerHeight;D[k+28>>2]=g[0];D[k+32>>2]=g[1];zc(d,f,k,b)&&c.preventDefault()}},W:c})}
function Fc(a,b,c,d,f,g){fc||(fc=Q(1684));a=Z(a);rc({target:a,N:"touchstart"==g||"touchend"==g,F:g,Y:d,$:function(c){c=c||window.event;for(var g={},k=0;k<c.touches.length;++k){var w=c.touches[k];g[w.identifier]=w}for(k=0;k<c.changedTouches.length;++k)w=c.changedTouches[k],g[w.identifier]=w,w.Jb=!0;for(k=0;k<c.targetTouches.length;++k)w=c.targetTouches[k],g[w.identifier].$b=!0;var v=w=fc;D[v+4>>2]=c.ctrlKey;D[v+8>>2]=c.shiftKey;D[v+12>>2]=c.altKey;D[v+16>>2]=c.metaKey;v+=20;var H=m.canvas?m.canvas.getBoundingClientRect():
void 0,J=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},K=0;for(k in g){var B=g[k];D[v>>2]=B.identifier;D[v+4>>2]=B.screenX;D[v+8>>2]=B.screenY;D[v+12>>2]=B.clientX;D[v+16>>2]=B.clientY;D[v+20>>2]=B.pageX;D[v+24>>2]=B.pageY;D[v+28>>2]=B.Jb;D[v+32>>2]=B.$b;H?(D[v+44>>2]=B.clientX-H.left,D[v+48>>2]=B.clientY-H.top):(D[v+44>>2]=0,D[v+48>>2]=0);D[v+36>>2]=B.clientX-J.left;D[v+40>>2]=B.clientY-J.top;v+=52;if(32<=++K)break}D[w>>2]=K;zc(d,f,w,b)&&c.preventDefault()},W:c})}
function Gc(a,b,c,d,f,g){function k(c){c=c||window.event;Cc(X,c,a);F[X+72>>3]=c.wheelDeltaX||0;F[X+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);F[X+88>>3]=0;D[X+96>>2]=0;zc(d,f,X,b)&&c.preventDefault()}function p(c){c=c||window.event;var g=X;Cc(g,c,a);F[g+72>>3]=c.deltaX;F[g+80>>3]=c.deltaY;F[g+88>>3]=c.deltaZ;D[g+96>>2]=c.deltaMode;zc(d,f,g,b)&&c.preventDefault()}X||(X=Q(104));rc({target:a,N:!0,F:g,Y:d,$:"wheel"==g?p:k,W:c})}
h={Za:1,jb:0,Wa:[],Me:{},i:[],Ge:[],Ue:[],ya:[],A:[],o:[],df:[],u:{},O:null,va:{},af:[],ha:{},Ze:{},pc:4,oa:function(){h.ob=new Float32Array(h.Ca);for(var a=0;a<h.Ca;a++)h.pb[a]=h.ob.subarray(0,a+1)},C:function(a){h.jb||(h.jb=a)},Z:function(a){for(var b=h.Za++,c=a.length;c<b;c++)a[c]=null;return b},Ca:256,ob:null,pb:[0],Qb:function(a,b,c,d){a="";for(var f=0;f<b;++f){var g=d?D[d+4*f>>2]:-1;a+=pa(D[c+4*f>>2],0>g?void 0:g)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||a.getContext("experimental-webgl",
b))&&h.bc(a,b)},bc:function(a,b){var c=Q(8),d={handle:c,attributes:b,version:b.mb,M:a};a.canvas&&(a.canvas.Eb=d);h.u[c]=d;("undefined"===typeof b.$a||b.$a)&&h.Sb(d);return c},nb:function(a){h.O=h.u[a];m.ma=l=h.O&&h.O.M;return!(a&&!l)},getContext:function(a){return h.u[a]},Ce:function(a){h.O===h.u[a]&&(h.O=null);if("object"===typeof sc)for(var b=h.u[a].M.canvas,c=0;c<Y.length;++c)Y[c].target!=b||lc(c--);h.u[a]&&h.u[a].M.canvas&&(h.u[a].M.canvas.Eb=void 0);Hc(h.u[a]);h.u[a]=null},Sb:function(a){a||
(a=h.O);if(!a.Tb){a.Tb=!0;var b=a.M;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,g){c.drawElementsInstancedANGLE(a,b,d,f,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.Ee=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}},ac:function(a){var b=h.i[a];a=h.ha[a]={A:{},Ja:0,ba:-1,da:-1};for(var c=a.A,d=l.getProgramParameter(b,35718),f=0;f<d;++f){var g=l.getActiveUniform(b,f),k=g.name;a.Ja=Math.max(a.Ja,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var p=l.getUniformLocation(b,k);if(p){var r=h.Z(h.A);c[k]=[g.size,r];h.A[r]=p;for(var w=1;w<g.size;++w)p=l.getUniformLocation(b,
k+"["+w+"]"),r=h.Z(h.A),h.A[r]=p}}}};var Ic=["default","low-power","high-performance"];function Jc(a,b){var c={};b>>=2;c.alpha=!!D[b];c.depth=!!D[b+1];c.stencil=!!D[b+2];c.antialias=!!D[b+3];c.premultipliedAlpha=!!D[b+4];c.preserveDrawingBuffer=!!D[b+5];c.powerPreference=Ic[D[b+6]];c.failIfMajorPerformanceCaveat=!!D[b+7];c.mb=D[b+8];c.Ne=D[b+9];c.$a=D[b+10];c.Lb=D[b+11];c.Qe=D[b+12];c.Te=D[b+13];a=xc(a);return!a||c.Lb?0:h.createContext(a,c)}
function Kc(a,b,c,d){for(var f=0;f<a;f++){var g=l[c](),k=g&&h.Z(d);g?(g.name=k,d[k]=g):h.C(1282);D[b+4*f>>2]=k}}function Lc(a,b,c,d){return b*(a*c+d-1&-d)}var Mc={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Nc={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Oc(a,b,c,d,f){if(b=Mc[b]*Nc[a])switch(c=f+Lc(c,d,b,h.pc),a){case 5121:return A.subarray(f,c);case 5126:return E.subarray(f>>2,c>>2);case 5125:case 34042:return xa.subarray(f>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return wa.subarray(f>>1,c>>1);default:h.C(1280)}else h.C(1280)}Ia();S=Array(4096);Jb(O,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");hb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Lb("/dev/null",259);gb(1280,kb);gb(1536,lb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(u)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){y("random_device")});I("/dev","random",b);I("/dev","urandom",b);U("/dev/shm");
U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");Jb({l:function(){var a=nb("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=tb[+c];if(!b)throw new M(9);a={parent:null,l:{rb:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");m.FS_createFolder=Tb;m.FS_createPath=Ub;m.FS_createDataFile=Wb;m.FS_createPreloadedFile=$b;m.FS_createLazyFile=Zb;m.FS_createLink=Xb;m.FS_createDevice=I;m.FS_unlink=Mb;
if(u){var fs=require("fs"),qb=require("path");R.mc()}u?uc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?uc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?uc=function(){return performance.now()}:uc=Date.now;m.requestFullScreen=function(a,b,c){n("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");m.requestFullScreen=m.requestFullscreen;e.xb(a,b,c)};
m.requestFullscreen=function(a,b,c){e.requestFullscreen(a,b,c)};m.requestAnimationFrame=function(a){e.requestAnimationFrame(a)};m.setCanvasSize=function(a,b,c){e.hc(a,b,c)};m.pauseMainLoop=function(){e.b.pause()};m.resumeMainLoop=function(){e.b.resume()};m.getUserMedia=function(){e.getUserMedia()};m.createContext=function(a,b,c,d){return e.createContext(a,b,c,d)};h.oa();function jb(a){var b=Array(qa(a)+1);a=C(a,b,0,b.length);b.length=a;return b}
var Qc=m.asm({},{abort:y,setTempRet0:function(a){la=a},getTempRet0:function(){return la},___cxa_pure_virtual:function(){z=!0;throw"Pure virtual function called!";},___lock:function(){},___setErrNo:Za,___syscall140:function(a,b){V=b;try{var c=bc();W();var d=W(),f=W(),g=W();Qb(c,d,g);D[f>>2]=c.position;c.Ha&&0===d&&0===g&&(c.Ha=null);return 0}catch(k){return"undefined"!==typeof ac&&k instanceof M||y(k),-k.D}},___syscall145:function(a,b){V=b;try{var c=bc(),d=W();a:{var f=W();for(b=a=0;b<f;b++){var g=
D[d+(8*b+4)>>2],k=c,p=D[d+8*b>>2],r=g,w=void 0,v=ta;if(0>r||0>w)throw new M(22);if(null===k.fd)throw new M(9);if(1===(k.flags&2097155))throw new M(9);if(P(k.node.mode))throw new M(21);if(!k.g.read)throw new M(22);var H="undefined"!==typeof w;if(!H)w=k.position;else if(!k.seekable)throw new M(29);var J=k.g.read(k,v,p,r,w);H||(k.position+=J);var K=J;if(0>K){var B=-1;break a}a+=K;if(K<g)break}B=a}return B}catch(Ra){return"undefined"!==typeof ac&&Ra instanceof M||y(Ra),-Ra.D}},___syscall146:function(a,
b){V=b;try{var c=bc(),d=W();a:{var f=W();for(b=a=0;b<f;b++){var g=Rb(c,ta,D[d+8*b>>2],D[d+(8*b+4)>>2],void 0);if(0>g){var k=-1;break a}a+=g}k=a}return k}catch(p){return"undefined"!==typeof ac&&p instanceof M||y(p),-p.D}},___syscall221:function(a,b){V=b;try{var c=bc();switch(W()){case 0:var d=W();return 0>d?-N.s:Ka(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=W(),c.flags|=d,0;case 12:return d=W(),va[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-N.s;
case 9:return Za(N.s),-1;default:return-N.s}}catch(f){return"undefined"!==typeof ac&&f instanceof M||y(f),-f.D}},___syscall5:function(a,b){V=b;try{var c=pa(W()),d=W(),f=W();return Ka(c,d,f).fd}catch(g){return"undefined"!==typeof ac&&g instanceof M||y(g),-g.D}},___syscall54:function(a,b){V=b;try{var c=bc(),d=W();switch(d){case 21509:case 21505:return c.tty?0:-N.L;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.L;case 21519:if(!c.tty)return-N.L;var f=W();return D[f>>
2]=0;case 21520:return c.tty?-N.s:-N.L;case 21531:a=f=W();if(!c.g.Vb)throw new M(25);return c.g.Vb(c,d,a);case 21523:return c.tty?0:-N.L;case 21524:return c.tty?0:-N.L;default:y("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof ac&&g instanceof M||y(g),-g.D}},___syscall6:function(a,b){V=b;try{var c=bc();Pb(c);return 0}catch(d){return"undefined"!==typeof ac&&d instanceof M||y(d),-d.D}},___unlock:function(){},__computeUnpackAlignedImageSize:Lc,__fillMouseEventData:Cc,__findCanvasEventTarget:xc,
__findEventTarget:Z,__glGenObject:Kc,__registerKeyEventCallback:yc,__registerMouseEventCallback:Dc,__registerTouchEventCallback:Fc,__registerUiEventCallback:Ec,__registerWheelEventCallback:Gc,_abort:function(){m.abort()},_emscripten_get_device_pixel_ratio:function(){return window.devicePixelRatio||1},_emscripten_get_element_css_size:function(a,b,c){a=a?Z(a):m.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),F[b>>3]=a.right-a.left,F[c>>3]=a.bottom-a.top):(F[b>>3]=a.clientWidth,
F[c>>3]=a.clientHeight);return 0},_emscripten_get_heap_size:function(){return G},_emscripten_get_now:uc,_emscripten_memcpy_big:function(a,b,c){A.set(A.subarray(b,b+c),a)},_emscripten_resize_heap:wc,_emscripten_set_canvas_cursor:function(a){document.getElementById("gameview").style.cursor=pa(a)},_emscripten_set_canvas_element_size:function(a,b,c){a=xc(a);if(!a)return-4;a.width=b;a.height=c;return 0},_emscripten_set_element_css_size:function(a,b,c){a=a?Z(a):m.canvas;if(!a)return-4;a.style.width=b+"px";
a.style.height=c+"px";return 0},_emscripten_set_keydown_callback_on_thread:function(a,b,c,d,f){yc(a,b,c,d,2,"keydown",f);return 0},_emscripten_set_keypress_callback_on_thread:function(a,b,c,d,f){yc(a,b,c,d,1,"keypress",f);return 0},_emscripten_set_keyup_callback_on_thread:function(a,b,c,d,f){yc(a,b,c,d,3,"keyup",f);return 0},_emscripten_set_main_loop:Ac,_emscripten_set_main_loop_timing:Bc,_emscripten_set_mousedown_callback_on_thread:function(a,b,c,d,f){Dc(a,b,c,d,5,"mousedown",f);return 0},_emscripten_set_mousemove_callback_on_thread:function(a,
b,c,d,f){Dc(a,b,c,d,8,"mousemove",f);return 0},_emscripten_set_mouseup_callback_on_thread:function(a,b,c,d,f){Dc(a,b,c,d,6,"mouseup",f);return 0},_emscripten_set_resize_callback_on_thread:function(a,b,c,d,f){Ec(a,b,c,d,10,"resize",f);return 0},_emscripten_set_touchcancel_callback_on_thread:function(a,b,c,d,f){Fc(a,b,c,d,25,"touchcancel",f);return 0},_emscripten_set_touchend_callback_on_thread:function(a,b,c,d,f){Fc(a,b,c,d,23,"touchend",f);return 0},_emscripten_set_touchmove_callback_on_thread:function(a,
b,c,d,f){Fc(a,b,c,d,24,"touchmove",f);return 0},_emscripten_set_touchstart_callback_on_thread:function(a,b,c,d,f){Fc(a,b,c,d,22,"touchstart",f);return 0},_emscripten_set_wheel_callback_on_thread:function(a,b,c,d,f){a=Z(a);return"undefined"!==typeof a.onwheel?(Gc(a,b,c,d,9,"wheel",f),0):"undefined"!==typeof a.onmousewheel?(Gc(a,b,c,d,9,"mousewheel",f),0):-1},_emscripten_webgl_create_context:function(a,b){return Jc(a,b)},_emscripten_webgl_do_create_context:Jc,_emscripten_webgl_init_context_attributes:function(a){a>>=
2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},_emscripten_webgl_make_context_current:function(a){return h.nb(a)?0:-5},_exit:function(a){Pc(a)},_glActiveTexture:function(a){l.activeTexture(a)},_glAttachShader:function(a,b){l.attachShader(h.i[a],h.o[b])},_glBindBuffer:function(a,b){l.bindBuffer(a,h.Wa[b])},_glBindTexture:function(a,b){l.bindTexture(a,h.ya[b])},_glBlendFunc:function(a,b){l.blendFunc(a,b)},_glBufferData:function(a,b,c,d){l.bufferData(a,c?A.subarray(c,c+b):
b,d)},_glBufferSubData:function(a,b,c,d){l.bufferSubData(a,b,A.subarray(d,d+c))},_glClear:function(a){l.clear(a)},_glClearColor:function(a,b,c,d){l.clearColor(a,b,c,d)},_glCompileShader:function(a){l.compileShader(h.o[a])},_glCreateProgram:function(){var a=h.Z(h.i),b=l.createProgram();b.name=a;h.i[a]=b;return a},_glCreateShader:function(a){var b=h.Z(h.o);h.o[b]=l.createShader(a);return b},_glDeleteProgram:function(a){if(a){var b=h.i[a];b?(l.deleteProgram(b),b.name=0,h.i[a]=null,h.ha[a]=null):h.C(1281)}},
_glDeleteShader:function(a){if(a){var b=h.o[a];b?(l.deleteShader(b),h.o[a]=null):h.C(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=h.ya[d];f&&(l.deleteTexture(f),f.name=0,h.ya[d]=null)}},_glDepthMask:function(a){l.depthMask(!!a)},_glDetachShader:function(a,b){l.detachShader(h.i[a],h.o[b])},_glDisable:function(a){l.disable(a)},_glDisableVertexAttribArray:function(a){l.disableVertexAttribArray(a)},_glDrawElements:function(a,b,c,d){l.drawElements(a,b,c,d)},_glEnable:function(a){l.enable(a)},
_glEnableVertexAttribArray:function(a){l.enableVertexAttribArray(a)},_glFinish:function(){l.finish()},_glGenBuffers:function(a,b){Kc(a,b,"createBuffer",h.Wa)},_glGenTextures:function(a,b){Kc(a,b,"createTexture",h.ya)},_glGetAttribLocation:function(a,b){return l.getAttribLocation(h.i[a],pa(b))},_glGetProgramInfoLog:function(a,b,c,d){a=l.getProgramInfoLog(h.i[a]);null===a&&(a="(unknown error)");0<b&&d?(b=C(a,A,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=h.Za)h.C(1281);
else{var d=h.ha[a];if(d)if(35716==b)a=l.getProgramInfoLog(h.i[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b)D[c>>2]=d.Ja;else if(35722==b){if(-1==d.ba){a=h.i[a];var f=l.getProgramParameter(a,35721);for(b=d.ba=0;b<f;++b)d.ba=Math.max(d.ba,l.getActiveAttrib(a,b).name.length+1)}D[c>>2]=d.ba}else if(35381==b){if(-1==d.da)for(a=h.i[a],f=l.getProgramParameter(a,35382),b=d.da=0;b<f;++b)d.da=Math.max(d.da,l.getActiveUniformBlockName(a,b).length+1);D[c>>2]=d.da}else D[c>>2]=l.getProgramParameter(h.i[a],
b);else h.C(1282)}else h.C(1281)},_glGetShaderInfoLog:function(a,b,c,d){a=l.getShaderInfoLog(h.o[a]);null===a&&(a="(unknown error)");0<b&&d?(b=C(a,A,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=l.getShaderInfoLog(h.o[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1):35720==b?(a=l.getShaderSource(h.o[a]),D[c>>2]=null===a||0==a.length?0:a.length+1):D[c>>2]=l.getShaderParameter(h.o[a],b):h.C(1281)},_glGetUniformLocation:function(a,b){b=pa(b);var c=0;if("]"==
b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=h.ha[a]&&h.ha[a].A[b])&&0<=c&&c<a[0]?a[1]+c:-1},_glLinkProgram:function(a){l.linkProgram(h.i[a]);h.ac(a)},_glScissor:function(a,b,c,d){l.scissor(a,b,c,d)},_glShaderSource:function(a,b,c,d){b=h.Qb(a,b,c,d);l.shaderSource(h.o[a],b)},_glTexImage2D:function(a,b,c,d,f,g,k,p,r){l.texImage2D(a,b,c,d,f,g,k,p,r?Oc(p,k,d,f,r,c):null)},_glTexParameteri:function(a,b,c){l.texParameteri(a,b,c)},_glUniform1f:function(a,
b){l.uniform1f(h.A[a],b)},_glUniform1i:function(a,b){l.uniform1i(h.A[a],b)},_glUniformMatrix4fv:function(a,b,c,d){if(16*b<=h.Ca)for(var f=h.pb[16*b-1],g=0;g<16*b;g+=16)f[g]=E[d+4*g>>2],f[g+1]=E[d+(4*g+4)>>2],f[g+2]=E[d+(4*g+8)>>2],f[g+3]=E[d+(4*g+12)>>2],f[g+4]=E[d+(4*g+16)>>2],f[g+5]=E[d+(4*g+20)>>2],f[g+6]=E[d+(4*g+24)>>2],f[g+7]=E[d+(4*g+28)>>2],f[g+8]=E[d+(4*g+32)>>2],f[g+9]=E[d+(4*g+36)>>2],f[g+10]=E[d+(4*g+40)>>2],f[g+11]=E[d+(4*g+44)>>2],f[g+12]=E[d+(4*g+48)>>2],f[g+13]=E[d+(4*g+52)>>2],f[g+
14]=E[d+(4*g+56)>>2],f[g+15]=E[d+(4*g+60)>>2];else f=E.subarray(d>>2,d+64*b>>2);l.uniformMatrix4fv(h.A[a],!!c,f)},_glUseProgram:function(a){l.useProgram(h.i[a])},_glVertexAttribPointer:function(a,b,c,d,f,g){l.vertexAttribPointer(a,b,c,!!d,f,g)},_glViewport:function(a,b,c,d){l.viewport(a,b,c,d)},_llvm_exp2_f32:function(a){return Math.pow(2,a)},_llvm_trap:function(){y("trap!")},abortOnCannotGrowMemory:function(){y("OOM")},emscriptenWebGLGetTexPixelData:Oc,emscripten_realloc_buffer:vc,tempDoublePtr:38096,
DYNAMICTOP_PTR:37856},buffer);m.asm=Qc;m.___em_js__emscripten_set_canvas_cursor=function(){return m.asm.___em_js__emscripten_set_canvas_cursor.apply(null,arguments)};m.___errno_location=function(){return m.asm.___errno_location.apply(null,arguments)};m._emscripten_replace_memory=function(){return m.asm._emscripten_replace_memory.apply(null,arguments)};var Hc=m._free=function(){return m.asm._free.apply(null,arguments)};m._llvm_maxnum_f32=function(){return m.asm._llvm_maxnum_f32.apply(null,arguments)};
m._llvm_minnum_f32=function(){return m.asm._llvm_minnum_f32.apply(null,arguments)};m._main=function(){return m.asm._main.apply(null,arguments)};var Q=m._malloc=function(){return m.asm._malloc.apply(null,arguments)};m._memcpy=function(){return m.asm._memcpy.apply(null,arguments)};m._memmove=function(){return m.asm._memmove.apply(null,arguments)};m._memset=function(){return m.asm._memset.apply(null,arguments)};m._sbrk=function(){return m.asm._sbrk.apply(null,arguments)};
m.establishStackSpace=function(){return m.asm.establishStackSpace.apply(null,arguments)};var Ya=m.globalCtors=function(){return m.asm.globalCtors.apply(null,arguments)},sa=m.stackAlloc=function(){return m.asm.stackAlloc.apply(null,arguments)};m.stackRestore=function(){return m.asm.stackRestore.apply(null,arguments)};m.stackSave=function(){return m.asm.stackSave.apply(null,arguments)};m.dynCall_fif=function(){return m.asm.dynCall_fif.apply(null,arguments)};
m.dynCall_ii=function(){return m.asm.dynCall_ii.apply(null,arguments)};m.dynCall_iii=function(){return m.asm.dynCall_iii.apply(null,arguments)};var zc=m.dynCall_iiii=function(){return m.asm.dynCall_iiii.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.dynCall_iiiiii.apply(null,arguments)};m.dynCall_j=function(){return m.asm.dynCall_j.apply(null,arguments)};m.dynCall_v=function(){return m.asm.dynCall_v.apply(null,arguments)};
m.dynCall_vi=function(){return m.asm.dynCall_vi.apply(null,arguments)};m.dynCall_vif=function(){return m.asm.dynCall_vif.apply(null,arguments)};m.dynCall_vii=function(){return m.asm.dynCall_vii.apply(null,arguments)};m.dynCall_viii=function(){return m.asm.dynCall_viii.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.dynCall_viiii.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm.dynCall_viiiii.apply(null,arguments)};
m.dynCall_viiiiii=function(){return m.asm.dynCall_viiiiii.apply(null,arguments)};m.asm=Qc;m.getMemory=function(a){if(Fa)var b=Q(a);else b=D[9464],a=b+a+15&-16,a<=G?D[9464]=a:wc(a)||(b=0);return b};m.addRunDependency=Pa;m.removeRunDependency=Qa;m.FS_createFolder=Tb;m.FS_createPath=Ub;m.FS_createDataFile=Wb;m.FS_createPreloadedFile=$b;m.FS_createLazyFile=Zb;m.FS_createLink=Xb;m.FS_createDevice=I;m.FS_unlink=Mb;
function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;Oa=function Rc(){m.calledRun||Sc();m.calledRun||(Oa=Rc)};
m.callMain=function(a){a=a||[];Ga();var b=a.length+1,c=sa(4*(b+1));D[c>>2]=ra(m.thisProgram);for(var d=1;d<b;d++)D[(c>>2)+d]=ra(a[d-1]);D[(c>>2)+b]=0;try{var f=m._main(b,c,0);Pc(f,!0)}catch(g){g instanceof fa||("SimulateInfiniteLoop"==g?m.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),n("exception thrown: "+a),m.quit(1,g)))}finally{}};
function Sc(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!z)){Ga();vb=!1;za(Ca);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&Tc&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Ea.unshift(b)}za(Ea)}}a=a||m.arguments;if(!(0<Ma)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)La();za(Aa);0<Ma||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=Sc;function Pc(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(z=!0,m.onExit))m.onExit(a);m.quit(a,new fa(a))}}function y(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ha(a),n(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=y;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var Tc=!0;m.noInitialRun&&(Tc=!1);m.noExitRuntime=!0;Sc();
